### ISSUE TITLE
it's can't run,please check it out

### ISSUE THREAD

**Issue by verring** [lijiejie/GitHack#11]
# python
Python 2.7.18 (default, Apr 28 2021, 17:39:59) 
[GCC 10.2.1 20210110] on linux2
Type "help", "copyright", "credits" or "license" for more information.

                                                                                                                      
┌──(root💀kali)-[/opt/GitHack-master]
└─# python GitHack.py http://127.0.0.1:80/.git/
[+] Download and parse index file ...
Traceback (most recent call last):
  File "GitHack.py", line 106, in <module>
    s = Scanner()
  File "GitHack.py", line 36, in __init__
    data = self._request_data(sys.argv[-1] + '/index')
  File "GitHack.py", line 54, in _request_data
    return urllib2.urlopen(request, context=context).read()
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 404: Not Found

**Comment by lijiejie** [comment]
Fail to download index file , check url below with browser 

http://127.0.0.1:80/.git/index

**Comment by verring** [comment]
> Fail to download index file , check url below with browser
> 
> http://127.0.0.1:80/.git/index

i got thank u so much~
